$file = "C:\Users\saeid\.gemini\antigravity\scratch\portfolio-site\index.html"
$enc = [System.Text.Encoding]::UTF8

# Start fresh
[System.IO.File]::WriteAllText($file, "", $enc)

function Append($text) {
    [System.IO.File]::AppendAllText($file, $text + "`n", $enc)
}

Append('<!DOCTYPE html>')
Append('<html lang="ar" dir="rtl">')
Append('<head>')
Append('<meta charset="UTF-8"/>')
Append('<meta name="viewport" content="width=device-width, initial-scale=1.0"/>')
Append('<title>مطور مواقع احترافي</title>')
Append('<link rel="preconnect" href="https://fonts.googleapis.com"/>')
Append('<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>')
Append('<style>')
Append('*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}')
Append('html{scroll-behavior:smooth}')
Append('body{font-family:Cairo,sans-serif;direction:rtl;color:#1a2340;background:#fff;line-height:1.7;overflow-x:hidden}')
Append('a{text-decoration:none;color:inherit}ul{list-style:none}img{max-width:100%;display:block}')
Append(':root{--navy:#1a2340;--blue:#2563eb;--blue-light:#3b82f6;--blue-soft:#eff6ff;--pink-soft:#fdf2f8;--mint-soft:#f0fdf4;--gray-soft:#f8fafc;--gray-200:#e2e8f0;--gray-400:#94a3b8;--gray-600:#64748b;--radius-sm:10px;--radius-md:16px;--radius-lg:24px;--radius-xl:32px;--shadow-sm:0 2px 12px rgba(0,0,0,.06);--shadow-md:0 8px 30px rgba(0,0,0,.10);--shadow-lg:0 16px 48px rgba(0,0,0,.12)}')
Append('.container{max-width:1180px;margin:0 auto;padding:0 24px}')
Append('.section-label{display:inline-flex;align-items:center;gap:6px;font-size:13px;font-weight:600;color:var(--blue);background:var(--blue-soft);border-radius:100px;padding:4px 14px;margin-bottom:16px}')
Append('.section-label::before{content:"u25CF";font-size:8px}')
Append('.btn{display:inline-flex;align-items:center;gap:8px;font-family:Cairo,sans-serif;font-weight:700;font-size:15px;border-radius:100px;padding:13px 28px;cursor:pointer;transition:all .25s;border:none}')
Append('.btn-primary{background:var(--blue);color:#fff}.btn-primary:hover{background:#1d4ed8;transform:translateY(-2px);box-shadow:0 8px 24px rgba(37,99,235,.35)}')
Append('.btn-outline{background:transparent;color:var(--navy);border:2px solid var(--gray-200)}.btn-outline:hover{border-color:var(--blue);color:var(--blue)}')
Append('.btn-white{background:#fff;color:var(--blue);font-weight:700}.btn-white:hover{background:#f0f7ff;transform:translateY(-2px)}')
Append('/* NAV */header{position:sticky;top:0;z-index:100;background:rgba(255,255,255,.96);backdrop-filter:blur(12px);border-bottom:1px solid var(--gray-200)}')
Append('.nav{display:flex;align-items:center;justify-content:space-between;height:68px}')
Append('.nav-logo{display:flex;flex-direction:column;line-height:1.2}')
Append('.logo-name{font-size:18px;font-weight:800;color:var(--navy)}.logo-sub{font-size:11px;color:var(--gray-400);font-weight:500}')
Append('.nav-links{display:flex;align-items:center;gap:32px}.nav-links a{font-size:14px;font-weight:600;color:var(--gray-600);transition:color .2s}.nav-links a:hover{color:var(--blue)}')
Append('.nav-actions{display:flex;align-items:center;gap:12px}')
Append('.nav-badge{display:flex;align-items:center;gap:6px;font-size:13px;font-weight:600;color:#16a34a;background:#f0fdf4;border-radius:100px;padding:6px 14px}')
Append('.nav-badge::before{content:"";width:8px;height:8px;border-radius:50%;background:#22c55e;display:block;box-shadow:0 0 0 3px rgba(34,197,94,.2)}')
Append('.hamburger{display:none;flex-direction:column;gap:5px;cursor:pointer;padding:4px}.hamburger span{display:block;width:24px;height:2px;background:var(--navy);border-radius:2px;transition:all .3s}')
Append('/* HERO */.hero{padding:80px 0 60px;background:#fff;position:relative;overflow:hidden}')
Append('.hero::before{content:"";position:absolute;top:-120px;left:-180px;width:500px;height:500px;border-radius:50%;background:radial-gradient(circle,rgba(37,99,235,.07) 0%,transparent 70%);pointer-events:none}')
Append('.hero::after{content:"";position:absolute;bottom:-80px;right:-120px;width:380px;height:380px;border-radius:50%;background:radial-gradient(circle,rgba(139,92,246,.06) 0%,transparent 70%);pointer-events:none}')
Append('.hero-inner{display:flex;align-items:center;gap:48px}.hero-text{flex:1}')
Append('.hero-tag{display:inline-flex;align-items:center;gap:8px;background:var(--blue-soft);color:var(--blue);border-radius:100px;padding:6px 16px;font-size:13px;font-weight:700;margin-bottom:20px}')
Append('.hero-tag .dot{width:8px;height:8px;border-radius:50%;background:var(--blue);box-shadow:0 0 0 3px rgba(37,99,235,.2)}')
Append('.hero h1{font-size:clamp(36px,5vw,58px);font-weight:900;line-height:1.15;color:var(--navy);margin-bottom:6px}')
Append('.hero h1 .accent{color:var(--blue)}.hero-desc{font-size:16px;color:var(--gray-600);max-width:520px;margin-bottom:32px}')
Append('.hero-cta{display:flex;gap:14px;flex-wrap:wrap;margin-bottom:40px}.hero-stats{display:flex;gap:32px;flex-wrap:wrap}')
Append('.hero-stat strong{display:block;font-size:24px;font-weight:900;color:var(--navy)}.hero-stat span{font-size:13px;color:var(--gray-600);font-weight:500}')
Append('.hero-visual{flex:0 0 420px;position:relative}')
Append('.hero-mockup{border-radius:var(--radius-lg);box-shadow:var(--shadow-lg);width:100%;border:4px solid #fff;outline:1px solid var(--gray-200)}')
Append('.hero-badge-float{position:absolute;bottom:-20px;right:-20px;background:#fff;border-radius:var(--radius-md);padding:12px 18px;box-shadow:var(--shadow-md);display:flex;align-items:center;gap:10px;font-size:13px;font-weight:700;color:var(--navy)}')
Append('.badge-icon{width:36px;height:36px;border-radius:10px;background:var(--blue-soft);display:flex;align-items:center;justify-content:center;font-size:18px}')
Append('/* PROJECTS */.projects{padding:80px 0}.projects-header{text-align:center;margin-bottom:60px}')
Append('.projects-header h2{font-size:clamp(28px,4vw,42px);font-weight:900;color:var(--navy)}.projects-header p{font-size:16px;color:var(--gray-600);margin-top:10px}')
Append('.project-block{margin-bottom:36px;border-radius:var(--radius-xl);overflow:hidden;display:grid;grid-template-columns:1fr 1fr;min-height:340px;box-shadow:var(--shadow-md)}')
Append('.project-block.reverse{direction:ltr}.project-block.reverse .project-info{direction:rtl}.project-block.reverse .project-img-wrap{direction:rtl}')
Append('.project-info{padding:48px 40px;display:flex;flex-direction:column;justify-content:center}')
Append('.project-number{font-size:12px;font-weight:700;color:var(--blue);letter-spacing:.08em;margin-bottom:10px}')
Append('.project-info h3{font-size:26px;font-weight:800;color:var(--navy);margin-bottom:12px;line-height:1.3}')
Append('.project-info p{font-size:14px;color:var(--gray-600);margin-bottom:24px;line-height:1.7}')
Append('.project-tags{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:24px}')
Append('.project-tag{background:rgba(37,99,235,.1);color:var(--blue);border-radius:100px;padding:4px 12px;font-size:12px;font-weight:700}')
Append('.project-link{display:inline-flex;align-items:center;gap:6px;font-size:14px;font-weight:700;color:var(--blue);transition:gap .2s}.project-link:hover{gap:10px}')
Append('.project-img-wrap{display:flex;align-items:center;justify-content:center;padding:32px}')
Append('.project-img-wrap img{border-radius:var(--radius-md);box-shadow:var(--shadow-lg);width:100%;max-width:520px;object-fit:cover;transition:transform .4s}')
Append('.project-block:hover .project-img-wrap img{transform:scale(1.02) translateY(-4px)}')
Append('/* SERVICES */.services{padding:80px 0;background:var(--gray-soft)}.services-header{text-align:center;margin-bottom:48px}')
Append('.services-header h2{font-size:clamp(26px,4vw,40px);font-weight:900;color:var(--navy)}.services-header p{font-size:16px;color:var(--gray-600);margin-top:10px}')
Append('.services-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}')
Append('.service-card{background:#fff;border-radius:var(--radius-lg);padding:32px 28px;box-shadow:var(--shadow-sm);border:1px solid var(--gray-200);transition:all .3s;position:relative;overflow:hidden}')
Append('.service-card:hover{box-shadow:var(--shadow-md);transform:translateY(-4px);border-color:rgba(37,99,235,.2)}')
Append('.service-num{font-size:48px;font-weight:900;color:rgba(37,99,235,.08);position:absolute;top:16px;left:20px;line-height:1}')
Append('.service-icon{width:52px;height:52px;border-radius:14px;background:var(--blue-soft);display:flex;align-items:center;justify-content:center;font-size:24px;margin-bottom:18px}')
Append('.service-card h3{font-size:18px;font-weight:800;color:var(--navy);margin-bottom:10px}')
Append('.service-card p{font-size:14px;color:var(--gray-600);line-height:1.7}')
Append('/* PROCESS */.process{padding:80px 0}.process-header{text-align:center;margin-bottom:56px}')
Append('.process-header h2{font-size:clamp(26px,4vw,40px);font-weight:900;color:var(--navy)}.process-header p{font-size:16px;color:var(--gray-600);margin-top:10px}')
Append('.process-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:0;position:relative}')
Append('.process-grid::before{content:"";position:absolute;top:38px;right:10%;left:10%;height:2px;background:linear-gradient(90deg,var(--blue) 0%,var(--gray-200) 100%);z-index:0}')
Append('.process-step{text-align:center;padding:0 16px;position:relative;z-index:1}')
Append('.step-circle{width:76px;height:76px;border-radius:50%;background:#fff;border:3px solid var(--blue);display:flex;align-items:center;justify-content:center;margin:0 auto 20px;font-size:22px;font-weight:900;color:var(--blue);box-shadow:var(--shadow-sm);transition:all .3s}')
Append('.process-step:hover .step-circle{background:var(--blue);color:#fff;box-shadow:0 8px 24px rgba(37,99,235,.35)}')
Append('.process-step h3{font-size:16px;font-weight:800;color:var(--navy);margin-bottom:8px}.process-step p{font-size:13px;color:var(--gray-600);line-height:1.6}')
Append('/* CONTACT */.contact{padding:80px 0;background:var(--gray-soft)}.contact-inner{display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:start}')
Append('.contact-info h2{font-size:clamp(26px,4vw,38px);font-weight:900;color:var(--navy);margin-bottom:16px;line-height:1.3}')
Append('.contact-info h2 .accent{color:var(--blue)}.contact-info p{font-size:15px;color:var(--gray-600);margin-bottom:32px}')
Append('.contact-detail{display:flex;align-items:center;gap:14px;margin-bottom:20px}')
Append('.contact-detail .icon{width:44px;height:44px;border-radius:12px;background:var(--blue-soft);display:flex;align-items:center;justify-content:center;font-size:20px;flex-shrink:0}')
Append('.contact-detail .text strong{display:block;font-size:14px;font-weight:700;color:var(--navy)}.contact-detail .text span{font-size:13px;color:var(--gray-600)}')
Append('.social-row{display:flex;gap:12px;margin-top:24px}')
Append('.social-btn{width:42px;height:42px;border-radius:12px;background:#fff;border:1px solid var(--gray-200);display:flex;align-items:center;justify-content:center;font-size:16px;transition:all .2s;cursor:pointer;text-decoration:none}')
Append('.social-btn:hover{border-color:var(--blue);background:var(--blue-soft)}')
Append('.contact-form{background:#fff;border-radius:var(--radius-xl);padding:40px 36px;box-shadow:var(--shadow-md);border:1px solid var(--gray-200)}')
Append('.contact-form h3{font-size:20px;font-weight:800;color:var(--navy);margin-bottom:24px}')
Append('.form-group{margin-bottom:18px}.form-group label{display:block;font-size:13px;font-weight:700;color:var(--navy);margin-bottom:8px}')
Append('.form-group input,.form-group textarea,.form-group select{width:100%;border:1.5px solid var(--gray-200);border-radius:var(--radius-sm);padding:12px 16px;font-family:Cairo,sans-serif;font-size:14px;color:var(--navy);background:#fafafa;transition:border-color .2s,box-shadow .2s;outline:none;direction:rtl}')
Append('.form-group input:focus,.form-group textarea:focus{border-color:var(--blue);background:#fff;box-shadow:0 0 0 3px rgba(37,99,235,.1)}')
Append('.form-group textarea{resize:vertical;min-height:120px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:14px}')
Append('/* FAQ */.faq{padding:80px 0}.faq-inner{display:grid;grid-template-columns:1fr 1.6fr;gap:60px;align-items:start}')
Append('.faq-left h2{font-size:clamp(24px,3.5vw,36px);font-weight:900;color:var(--navy);line-height:1.35;margin-bottom:16px}')
Append('.faq-left h2 .accent{color:var(--blue)}.faq-left p{font-size:15px;color:var(--gray-600);margin-bottom:28px}')
Append('.faq-list{display:flex;flex-direction:column;gap:12px}')
Append('.faq-item{background:#fff;border:1px solid var(--gray-200);border-radius:var(--radius-md);overflow:hidden;box-shadow:var(--shadow-sm);transition:box-shadow .2s}')
Append('.faq-item:hover{box-shadow:var(--shadow-md)}')
Append('.faq-q{display:flex;justify-content:space-between;align-items:center;padding:18px 22px;cursor:pointer;font-size:15px;font-weight:700;color:var(--navy);user-select:none}')
Append('.faq-icon{width:28px;height:28px;border-radius:8px;background:var(--blue-soft);display:flex;align-items:center;justify-content:center;color:var(--blue);font-size:16px;flex-shrink:0;transition:transform .3s,background .2s}')
Append('.faq-item.open .faq-icon{transform:rotate(45deg);background:var(--blue);color:#fff}')
Append('.faq-a{max-height:0;overflow:hidden;transition:max-height .35s ease,padding .35s;font-size:14px;color:var(--gray-600);line-height:1.7}')
Append('.faq-item.open .faq-a{max-height:300px;padding:0 22px 18px}')
Append('/* CTA */.cta-strip{background:var(--navy);padding:80px 0;text-align:center;position:relative;overflow:hidden}')
Append('.cta-strip::before{content:"";position:absolute;top:-100px;left:50%;transform:translateX(-50%);width:600px;height:400px;border-radius:50%;background:radial-gradient(circle,rgba(37,99,235,.25) 0%,transparent 70%)}')
Append('.cta-strip h2{font-size:clamp(28px,4vw,46px);font-weight:900;color:#fff;margin-bottom:16px;position:relative}')
Append('.cta-strip h2 .accent{color:var(--blue-light)}.cta-strip p{font-size:16px;color:rgba(255,255,255,.65);margin-bottom:36px;position:relative}')
Append('.cta-btns{display:flex;justify-content:center;gap:16px;flex-wrap:wrap;position:relative}')
Append('/* FOOTER */footer{background:#0f172a;color:rgba(255,255,255,.7);padding:56px 0 32px}')
Append('.footer-inner{display:grid;grid-template-columns:1.5fr 1fr 1fr 1fr;gap:40px;margin-bottom:48px}')
Append('.footer-brand .logo-name{font-size:22px;font-weight:900;color:#fff;margin-bottom:10px}.footer-brand p{font-size:13px;line-height:1.7;margin-bottom:20px}')
Append('.footer-social{display:flex;gap:10px}')
Append('.footer-social a{width:36px;height:36px;border-radius:10px;background:rgba(255,255,255,.08);display:flex;align-items:center;justify-content:center;font-size:16px;transition:background .2s}.footer-social a:hover{background:var(--blue)}')
Append('.footer-col h4{font-size:14px;font-weight:800;color:#fff;margin-bottom:16px}')
Append('.footer-col ul{display:flex;flex-direction:column;gap:10px}.footer-col ul li a{font-size:13px;color:rgba(255,255,255,.6);transition:color .2s}.footer-col ul li a:hover{color:#fff}')
Append('.footer-bottom{border-top:1px solid rgba(255,255,255,.08);padding-top:24px;display:flex;justify-content:space-between;align-items:center;font-size:13px;flex-wrap:wrap;gap:12px}')
Append('.copy{color:rgba(255,255,255,.45)}.footer-links{display:flex;gap:20px}.footer-links a{color:rgba(255,255,255,.45);transition:color .2s}.footer-links a:hover{color:#fff}')
Append('/* RESPONSIVE */@media(max-width:1024px){.hero-inner{flex-direction:column}.hero-visual{flex:unset;width:100%;max-width:580px;margin:0 auto}.footer-inner{grid-template-columns:1fr 1fr}.project-block{grid-template-columns:1fr}.project-block.reverse{direction:rtl}.project-img-wrap{order:-1}.process-grid::before{display:none}.services-grid{grid-template-columns:repeat(2,1fr)}}')
Append('@media(max-width:768px){.nav-links{display:none}.nav-badge{display:none}.hamburger{display:flex}.nav-links.open{display:flex;flex-direction:column;gap:0;position:absolute;top:68px;right:0;left:0;background:#fff;border-bottom:1px solid var(--gray-200);padding:12px 0;z-index:99;box-shadow:var(--shadow-md)}.nav-links.open a{padding:13px 24px;width:100%;border-bottom:1px solid var(--gray-200)}header{position:relative}.hero{padding:48px 0 40px}.hero-stats{gap:20px}.hero-cta{gap:10px}.btn{font-size:14px;padding:11px 22px}.contact-inner{grid-template-columns:1fr;gap:32px}.faq-inner{grid-template-columns:1fr;gap:32px}.form-row{grid-template-columns:1fr}.footer-inner{grid-template-columns:1fr 1fr;gap:28px}.footer-bottom{flex-direction:column;gap:12px;text-align:center}.process-grid{grid-template-columns:1fr 1fr;gap:32px}.services-grid{grid-template-columns:1fr 1fr}}')
Append('@media(max-width:480px){.hero h1{font-size:30px}.footer-inner{grid-template-columns:1fr}.project-info{padding:28px 22px}.project-img-wrap{padding:20px}.project-info h3{font-size:20px}.contact-form{padding:28px 20px}.services-grid{grid-template-columns:1fr}.process-grid{grid-template-columns:1fr}}')
Append('</style></head><body>')

Write-Host "Script written successfully"